//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NiSceneGraphOptimization.rc
//
#define IDD_OPTIMIZATION_OPTIONS        500
#define IDC_OPT_CHECK_REMOVEDUPPROPERTIES 1000
#define IDC_OPT_CHECK_REMOVEBADTEXTURINGPROPS 1001
#define IDC_OPT_CHECK_REMOVEMULTIMTLNODES 1002
#define IDC_OPT_CHECK_REMOVECHILDLESSNODES 1003
#define IDC_OPT_CHECK_REMOVESINGLECHILDNODES 1004
#define IDC_OPT_CHECK_MERGESIBLINGNODES 1005
#define IDC_OPT_CHECK_MERGESIBLINGTRISHAPES 1006
#define IDC_OPT_CHECK_OPTIMIZETRISHAPES 1007
#define IDC_OPT_CHECK_REMOVEEXTRAUVSETS 1008
#define IDC_OPT_CHECK_REMOVEUNNECESSARYNORMALS 1009
#define IDC_OPT_CHECK_REMOVEUNNECESSARYVISCONTROLLERS 1010
#define IDC_OPT_CHECK_REMOVEUNNECESSARYLOOKATCONTROLLERS 1011
#define IDC_OPT_CHECK_NOMERGEONALPHA    1012
#define IDC_OPT_EDIT_ANIMATIONKEYREDUCTIONTOLERANCE 1013
#define IDC_OPT_CHECK_REMOVEHIDDENBONEMESH 1014
#define IDC_OPT_CHECK_REDUCEANIMATIONKEYS 1015
#define IDC_OPT_CHECK_REMOVEUNNECESSARYEXTRADATA 1016
#define IDC_OPT_CHECK_SORTBYTEXTURINGPROP 1017
#define IDC_OPT_CHECK_REMOVESGOKEEPTAGS 1018
#define IDC_OPT_RADIO_REMOVENAMES       1019
#define IDC_OPT_RADIO_NAMEUNNAMEDOBJECTS 1020
#define IDC_OPT_RADIO_LEAVENAMES        1021
#define IDC_OPT_BUTTON_RESETDEFAULTS    1022
#define IDC_OPT_RADIO_SKINHW            1023
#define IDC_OPT_RADIO_SKINSW            1024
#define IDC_OPT_EDIT_BONESPERPARTITION  1026
#define IDC_OPT_BUTTON_UNCHECKALL       1027
#define IDC_OPT_EDIT_MESHSIZEMODIFIER   1028
#define IDC_OPT_EDIT_MESHNORMALMODIFIER 1029
#define IDC_OPT_CHECK_WELDSKIN          1031
#define IDC_OPT_EDIT_MESHPOSITIONMODIFIER 1032
#define IDC_OPT_EDIT_DX9_MESHCACHESIZE  1033
#define IDC_OPT_EDIT_D3D10_MESHCACHESIZE 1034
#define IDC_OPT_EDIT_XENON_MESHCACHESIZE 1035
#define IDC_OPT_EDIT_PS3_MESHCACHESIZE  1036
#define IDC_OPT_EDIT_PS3_MESHCACHESIZE2 1037
#define IDC_OPT_EDIT_WII_MESHCACHESIZE  1037

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        501
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1035
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
