//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NiControllerExtractor.rc
//
#define IDD_OPTIONS                     101
#define IDD_CHOOSEACTOR                 102
#define IDC_RADIO_SINGLE_KF             1000
#define IDC_RADIO_MULTIPLE_KF           1001
#define IDC_CHECK_EXPORTED_FILE_NAME    1002
#define IDC_CHECK_CHARACTER_NAME        1003
#define IDC_RADIO_UPPER_CASE            1005
#define IDC_RADIO_LOWER_CASE            1006
#define IDC_EDIT_SEPARATOR              1008
#define IDC_STATIC_KF_FILENAME          1009
#define IDC_CHECK_CREATE_KFM            1012
#define IDC_EDIT_TRANS_DURATION         1013
#define IDC_EDIT_SYNC_TRANS_DURATION    1013
#define IDC_LIST_ACTOR_ROOTS            1014
#define IDC_EDIT_TRANS_DURATION2        1014
#define IDC_EDIT_NONSYNC_TRANS_DURATION 1014
#define IDC_CHECK_CHARACTER_NAME_IN_KFM_FILE 1015
#define IDC_COMBO_SYNC_TRANS_TYPE       1017
#define IDC_COMBO_NONSYNC_TRANS_TYPE    1018
#define IDC_COMPRESSION_ALWAYSCHECK     1022
#define IDC_CHECK_EXCLUDEFLIPCONTROLLERS 1024
#define IDC_CHECK_EXCLUDECUSTOMCONTROLLERS 1025
#define IDC_EDIT_EXCLUDEDCONTROLLERTYPES 1026
#define IDC_CHECK1                      1027
#define IDC_CHECK_EXCLUDEPSRESET        1027

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
