//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AssetAnalyzerDLL.rc
//
#define IDD_EXPORT_DIALOG               101
#define IDD_PROCESS_DIALOG              102
#define IDD_RESULTS_DIALOG              103
#define IDC_SAMPLE_BOOL                 1000
#define IDC_EDIT_SAMPLE_FLOAT           1001
#define IDC_EDIT_SAMPLE_STRING          1002
#define IDC_EDIT_SAMPLE_INT             1003
#define IDC_USE_MAX_TRIANGLE_COUNT      1004
#define IDC_MAX_TRIANGLE_COUNT          1006
#define IDC_USE_MAX_TEXTURE_SIZE        1007
#define IDC_USE_MAX_MEMORY_SIZE         1009
#define IDC_MAX_MEMORY_SIZE             1010
#define IDC_USE_TRIANGLE_MESH_RATIO 1011
#define IDC_TRIANGLE_TO_MESH_RATIO  1012
#define IDC_USE_MAX_SCENE_TEXTURE_SIZE  1015
#define IDC_MAX_SCENE_TEXTURE_SIZE      1016
#define IDC_USE_MULTI_SUBOBJECT_WARNING 1018
#define IDC_MULTI_SUB_OBJECT_WARNINGS   1019
#define IDC_USE_MAX_MORPHING_VERTEX_COUNT 1020
#define IDC_MAX_MORPHING_VERTEX_COUNT   1021
#define IDC_USE_MAX_TRIANGLES_PER_OBJECT 1022
#define IDC_MAX_TRIANGLES_PER_OBJECT    1023
#define IDC_USE_MAX_SCENE_GRAPH_DEPTH   1024
#define IDC_MAX_SCENE_GRAPH_DEPTH       1025
#define IDC_USE_MAX_LIGHTS_PER_OBJECT   1026
#define IDC_MAX_LIGHTS_PER_OBJECT       1027
#define IDC_USE_MAX_SCENE_OBJECT_COUNT  1028
#define IDC_MAX_SCENE_OBJECT_COUNT      1029
#define IDC_USE_REQUIRED_OBJECTS        1030
#define IDC_EDIT_RESULTS                1036
#define IDC_NEW_REQUIRED_OBJECT         1039
#define IDC_ADD_REQUIRED_OBJECT         1040
#define IDC_REQUIRED_OBJECTS            1041
#define IDC_MAX_TEXTURE_SIZE            1042
#define IDC_NO_SPOT_LIGHTS              1043
#define IDC_NO_DIRECTIONAL_LIGHTS       1044
#define IDC_NO_POINT_LIGHTS             1045
#define IDC_NO_AMBIENT_LIGHTS           1046

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
