// EMERGENT GAME TECHNOLOGIES PROPRIETARY INFORMATION
//
// This software is supplied under the terms of a license agreement or
// nondisclosure agreement with Emergent Game Technologies and may not 
// be copied or disclosed except in accordance with the terms of that 
// agreement.
//
//      Copyright (c) 1996-2008 Emergent Game Technologies.
//      All Rights Reserved.
//
// Emergent Game Technologies, Chapel Hill, North Carolina 27517
// http://www.emergent.net
//---------------------------------------------------------------------------
#include "NiMath.cpp"
#include "NiPoint2.cpp"
#include "NiPoint3.cpp"
#include "NiPoint3_PS3.cpp"
#include "NiPoint4_PS3.cpp"
#include "NiColor.cpp"
#include "NiBound.cpp"
#include "NiBound_PS3.cpp"
#include "NiQuaternion.cpp"
#include "NiQuaternion_PS3.cpp"
#include "NiTransform.cpp"
#include "NiMatrix3.cpp"

#if 0
#include "NiRTTI.cpp"
#include "NiTPointerAllocator.cpp"
#include "NiObject.cpp"
#include "NiObjectNET.cpp"
#include "NiString.cpp"
#include "NiGlobalStringTable.cpp"
#include "NiPlane.cpp"
#include "NiRefObject.cpp"

#include "NiExtraData.cpp"
#include "NiStringExtraData.cpp"
#include "NiStringsExtraData.cpp"
#include "NiSwitchStringExtraData.cpp"
#include "NiBooleanExtraData.cpp"
#include "NiFloatExtraData.cpp"
#include "NiFloatsExtraData.cpp"
#include "NiBinaryExtraData.cpp"
#include "NiVertWeightsExtraData.cpp"
#include "NiIntegerExtraData.cpp"
#include "NiIntegersExtraData.cpp"
#include "NiColorExtraData.cpp"
//#include "NiSCMExtraData.cpp"
#include "NiVectorExtraData.cpp"

#include "NiProperty.cpp"
#include "NiPropertyState.cpp"
#endif

#if 0
#include "NiFogProperty.cpp"
#include "NiWireframeProperty.cpp"
#include "NiZBufferProperty.cpp"
#include "NiStencilProperty.cpp"
#include "NiAlphaProperty.cpp"
#include "NiShadeProperty.cpp"
#include "NiSpecularProperty.cpp"
#include "NiDitherProperty.cpp"
#include "NiVertexColorProperty.cpp"
#include "NiTexturingProperty.cpp"
#include "NiMaterialProperty.cpp"
#include "NiRendererSpecificProperty.cpp"
#endif

#if 0
#include "NiAVObject.cpp"
#include "NiAVObject_PS3.cpp"
#include "NiCollisionObject.cpp"
#include "NiNode.cpp"
#include "NiCullingProcess.cpp"
//#include "NiCamera.cpp"
#endif

#if 0
//#include "NiObjectGroup.cpp"
//#include "NiFrustum.cpp"
//#include "NiFrustumPlanes.cpp"
//#include "NiAVObjectPalette.cpp"
//#include "NiPixelData_PS3.cpp"
//#include "NiMesh.cpp"
//#include "NiVisibleArray.cpp"
#endif

#if 0
#include "NiDynamicEffect.cpp"
#include "NiAmbientLight.cpp"
#include "NiDirectionalLight.cpp"
#include "NiLight.cpp"
#include "NiPointLight.cpp"
#include "NiSpotLight.cpp"
#include "NiDynamicEffectState.cpp"
#endif


#if 0
//#include "NiCulledObjectValidator.cpp"

//#include "NiMeshQuery.cpp"
//#include "NiSwitchNode.cpp"
#endif

// Excluded
//#include "NiParallelUpdateTaskManager.cpp"
//#include "NiTask.cpp"
//#include "NiTaskManager.cpp"
//#include "NiSkinData.cpp"
//#include "NiSkinInstance.cpp"
//#include "NiSkinPartition.cpp"
//#include "NiGeometryGroupManager.cpp"
//#include "NiGeometry.cpp"
//#include "NiGeometryData.cpp"
//#include "NiGPUProgram.cpp"
//#include "NiGPUProgramCache.cpp"
//#include "NiGPUProgramDescriptor.cpp"
//#include "NiImageConverter.cpp"
//#include "NiDevImageConverter.cpp"
//#include "NiTriBasedGeom.cpp"
//#include "NiTriBasedGeomData.cpp"
//#include "NiTriShape.cpp"
//#include "NiTriShapeData.cpp"
//#include "NiTriShapeDynamicData.cpp"
//#include "NiTriStrips.cpp"
//#include "NiTriStripsData.cpp"
//#include "NiViewerStrings.cpp"
//#include "NiViewRenderClick.cpp"
//#include "NiTexture.cpp"
//#include "NiTextureCodec.cpp"
//#include "NiTextureEffect.cpp"
//#include "NiTextureTransform.cpp"
//#include "NiTGAReader.cpp"
//#include "NiTimeController.cpp"
//#include "NiTimeSyncController.cpp"


//#include "NiSkinInstance_PS3.cpp"
//#include "NiTriShapeData_PS3.cpp"
//#include "NiTriStripsData_PS3.cpp"
//#include "NiProcessor.cpp"
//#include "NiVSMBlurMaterial.cpp"
//#include "NiVSMBlurMaterialDescriptor.cpp"
//#include "NiVSMBlurPixelProgramDescriptor.cpp"
//#include "NiVSMBlurVertexProgramDescriptor.cpp"
//#include "NiVSMShadowTechnique.cpp"
//#include "NiVSMBlurMaterialNodeLibrary.cpp"
//#include "NiSpotShadowWriteMaterial.cpp"
//#include "NiSpotShadowWriteMaterialNodeLibrary.cpp"
//#include "NiStandardMaterial.cpp"
//#include "NiStandardMaterialNodeLibrary.cpp"
//#include "NiStandardMaterialDescriptor.cpp"
//#include "NiStandardPixelProgramDescriptor.cpp"
//#include "NiStandardVertexProgramDescriptor.cpp"
//#include "Ni2DBuffer.cpp"
//#include "Ni2DRenderView.cpp"
//#include "Ni3DRenderView.cpp"
//#include "NiAccumulator.cpp"
//#include "NiAccumulatorProcessor.cpp"
//#include "NiAdditionalGeometryData.cpp"
//#include "NiAlphaAccumulator.cpp"
//#include "NiAlphaSortProcessor.cpp"
//#include "NiBackToFrontAccumulator.cpp"
//#include "NiBackToFrontSortProcessor.cpp"
//#include "NiBillboardNode.cpp"
//#include "NiBMPReader.cpp"
//#include "NiBSPNode.cpp"
//#include "NiClickRenderStep.cpp"
//#include "NiCodeBlock.cpp"
//#include "NiCommonSemantics.cpp"
//#include "NiCompositeValidator.cpp"
//#include "NiCompUtility.cpp"
//#include "NiDDSReader.cpp"
//#include "NiDefaultAVObjectPalette.cpp"
//#include "NiDefaultClickRenderStep.cpp"
//#include "NiDefaultShadowClickGenerator.cpp"
//#include "NiDepthStencilBuffer.cpp"
//#include "NiDirectionalShadowWriteMaterial.cpp"
//#include "NiDirectionalShadowWriteMaterialNodeLibrary.cpp"
//#include "NiDrawSceneUtility.cpp"
//#include "NiDynamicTexture.cpp"
//#include "NiFragmentMaterial.cpp"
//#include "NiFragmentShaderInstanceDescriptor.cpp"
//#include "NiLines.cpp"
//#include "NiLinesData.cpp"
//#include "NiLODData.cpp"
//#include "NiLODNode.cpp"
//#include "NiLogicalANDCompositeValidator.cpp"
//#include "NiMainMetrics.cpp"
//#include "NiMainSDM.cpp"
//#include "NiMaterial.cpp"
//#include "NiMaterialConfigurator.cpp"
//#include "NiMaterialDescriptor.cpp"
//#include "NiMaterialFragmentNode.cpp"
//#include "NiMaterialInstance.cpp"
//#include "NiMaterialLibrary.cpp"
//#include "NiMaterialNode.cpp"
//#include "NiMaterialNodeLibrary.cpp"
//#include "NiMaterialResource.cpp"
//#include "NiMaterialResourceBinding.cpp"
//#include "NiMaterialResourceConsumerNode.cpp"
//#include "NiMaterialResourceProducerNode.cpp"
//#include "NiMaterialSwapProcessor.cpp"//#include "NiMetricsLayer.cpp"
//#include "NiNIFImageReader.cpp"
//#include "NiOldScreenSpace.cpp"
//#include "NiPalette.cpp"
//#include "NiParticles.cpp"
//#include "NiParticlesData.cpp"
//#include "NiPersistentSrcTextureRendererData.cpp"
//#include "NiPixelData.cpp"
//#include "NiPixelFormat.cpp"
//#include "NiPointShadowWriteMaterial.cpp"
//#include "NiPointShadowWriteMaterialNodeLibrary.cpp"
//#include "NiRangeLODData.cpp"
//#include "NiRenderClick.cpp"
//#include "NiRenderClickValidator.cpp"
//#include "NiRenderedCubeMap.cpp"
//#include "NiRenderedTexture.cpp"
//#include "NiRenderer.cpp"
//#include "NiRenderFrame.cpp"
//#include "NiRenderListProcessor.cpp"
//#include "NiRenderStep.cpp"
//#include "NiRenderTargetGroup.cpp"
//#include "NiRenderView.cpp"
//#include "NiScreenElements.cpp"
//#include "NiScreenElementsData.cpp"
//#include "NiScreenFillingRenderView.cpp"
//#include "NiScreenLODData.cpp"
//#include "NiScreenTexture.cpp"
//#include "NiScreenTextureRenderClick.cpp"
//#include "NiSemanticAdapterTable.cpp"
//#include "NiSGIReader.cpp"
//#include "NiShader.cpp"
//#include "NiShaderAttributeDesc.cpp"
//#include "NiShaderConstantMap.cpp"
//#include "NiShaderConstantMapEntry.cpp"
//#include "NiShaderDeclaration.cpp"
//#include "NiShaderDesc.cpp"
//#include "NiShaderDescBase.cpp"
//#include "NiShaderError.cpp"
//#include "NiShaderFactory.cpp"
//#include "NiShaderLibrary.cpp"
//#include "NiShaderLibraryDesc.cpp"
//#include "NiShaderRequirementDesc.cpp"
//#include "NiShaderTimeController.cpp"
//#include "NiShadowClickGenerator.cpp"
//#include "NiShadowClickValidator.cpp"
//#include "NiShadowCubeMap.cpp"
//#include "NiShadowGenerator.cpp"
//#include "NiShadowManager.cpp"
//#include "NiShadowMap.cpp"
//#include "NiShadowRenderClick.cpp"
//#include "NiShadowTechnique.cpp"
//#include "NiSingleShaderMaterial.cpp"
//#include "NiSingleShaderMaterialLibrary.cpp"
//#include "NiSortAdjustNode.cpp"
//#include "NiSourceCubeMap.cpp"
//#include "NiSourceTexture.cpp"
//#include "NiGlobalConstantEntry.cpp"
