// EMERGENT GAME TECHNOLOGIES PROPRIETARY INFORMATION
//
// This software is supplied under the terms of a license agreement or
// nondisclosure agreement with Emergent Game Technologies and may not 
// be copied or disclosed except in accordance with the terms of that 
// agreement.
//
//      Copyright (c) 1996-2008 Emergent Game Technologies.
//      All Rights Reserved.
//
// Emergent Game Technologies, Chapel Hill, North Carolina 27517
// http://www.emergent.net

// Gamebryo Export Plugin
// Initial code generated by XSI SDK Wizard
// Executed Fri Feb 22 12:01:24 EST 2008 by pbaillargeon
// 
// Tip: You need to compile the generated code before you can load the plugin.
//      You might also need what is known in "the business" as a "compiler".
//      Oh!, and maybe a computer also. And electricity. Yeah, electricity
//      is probably needed. The universe might also be a pre-requisite,
//      we're not sure yet.
// After you compile the plugin, you can load it by clicking Update All in the Plugin Manager.

#include "CrosswalkGamebryoConverter.h"
#include "CrosswalkGamebryoInit.h"
#include "CrosswalkGamebryoLogger.h"
#include "CrosswalkGamebryoHelpers.h"

#include "XSIImportPluginLogger.h"

#include "NiPluginToolkit.h"
#include "NiXMLLogger.h"
#include "NiExporterOptionsSharedData.h"
#include "NiFilename.h"
#include "NiMain.h"
#include "NiMesh.h"
#include "NiMorphWeightsController.h"
#include "NiTransformController.h"

#include "tinyxml.h"

#include <direct.h>

#include <NiRendererSharedData.h>

#include <NiDefaultScriptReader.h>

//---------------------------------------------------------------------------
// Helpers
//---------------------------------------------------------------------------
namespace
{
    //---------------------------------------------------------------------------
    // Retrieve a string or use a default value if empty.
    //---------------------------------------------------------------------------
    const char* RetrieveValidString(const NiString& in_String, const char* in_Default)
    {
        return in_String.IsEmpty() ? in_Default : in_String;
    }

    //---------------------------------------------------------------------------
    // Automatically change the current directory. Helps find image files.
    //---------------------------------------------------------------------------
    class AutoChangeCurDir
    {
    public:
        AutoChangeCurDir(const char* in_NewCurDir)
        {
            char* cwd = _getcwd(NULL, 0);
            if (cwd)
            {
                m_PrevCurDir = cwd;
                free(cwd);
            }
            _chdir(in_NewCurDir);
        }
        ~AutoChangeCurDir()
        {
            if (m_PrevCurDir.size() > 0 )
                _chdir(m_PrevCurDir.c_str());
        }

    private:
        std::string m_PrevCurDir;
    };

    //---------------------------------------------------------------------------
    // Setup the Gamebryo XML logger in the shared data.
    //---------------------------------------------------------------------------
    bool SetupGamebryoLogging(
        const epg::ConverterSettings& in_Settings,
        NiXMLLogger& kLogger,
        NiString& out_LogFilename,
        bool& out_IsTemp)
    {
        out_IsTemp = false;

        NiSharedDataList* pkDataList = NiSharedDataList::GetInstance();
        if (pkDataList)
        {
            pkDataList->Lock();
            {
                pkDataList->DeleteAll();
                // Note: it is important to always create the NiExporterOptionsSharedData,
                //       otherwise some plugin in the pipeline may crash due to
                //       using uninitialized pointers.
                NiExporterOptionsSharedDataPtr spEOSharedData = 
                    NiNew NiExporterOptionsSharedData();

                out_LogFilename = in_Settings.GetLogFileName();
                if (out_LogFilename.IsEmpty())
                {
                    out_IsTemp = true;
                    TCHAR tempPath[MAX_PATH];
                    DWORD len = ::GetTempPath(MAX_PATH, tempPath);
                    if (0 != len && len < MAX_PATH)
                    {
                        TCHAR tempFileName[MAX_PATH];
                        if (0 != ::GetTempFileName(tempPath, "gblog", 0, tempFileName))
                        {
                            out_LogFilename = tempFileName;
                        }
                    }
                }

                if (!out_LogFilename.IsEmpty())
                {
                    kLogger.CreateLog(out_LogFilename);
                    spEOSharedData->SetWriteResultsToLog(true);
                    spEOSharedData->SetXMLLogger(&kLogger);
                }
                else
                {
                    spEOSharedData->SetWriteResultsToLog(false);
                    spEOSharedData->SetXMLLogger(0);
                }

                pkDataList->Insert(spEOSharedData);
            }
            pkDataList->Unlock();
        }

        return true;
    }

    //---------------------------------------------------------------------------
    // Setup the Gamebryo engine target platform.
    //---------------------------------------------------------------------------
    bool SetTargetPlatform(epg::TargetPlatform in_Platform, epg::Logger& in_Logger)
    {
        NiSystemDesc::RendererID renderer = NiSystemDesc::RENDERER_GENERIC;

        switch (in_Platform)
        {
            case epg::GENERIC_PLATFORM:
                renderer = NiSystemDesc::RENDERER_GENERIC;
                break;
            case epg::DIRECTX_9_PLATFORM:
                renderer = NiSystemDesc::RENDERER_DX9;
                break;
            case epg::DIRECTX_10_PLATFORM:
                renderer = NiSystemDesc::RENDERER_D3D10;
                break;
            case epg::XBOX_360_PLATFORM:
                renderer = NiSystemDesc::RENDERER_XENON;
                break;
            case epg::PS3_PLATFORM:
                renderer = NiSystemDesc::RENDERER_PS3;
                break;
            case epg::WII_PLATFORM:
                renderer = NiSystemDesc::RENDERER_WII;
                break;
            default:
                return in_Logger.Log(epg::LOG_ERROR, "Unknown target platform requested.");
        }

        NiSystemDesc::GetSystemDesc().SetToolModeRendererID(renderer);

        return true;
    }

    //---------------------------------------------------------------------------
    // Create a default script when no script provided.
    //---------------------------------------------------------------------------
    NiScriptInfoPtr CreateDefaultGamebryoScript(const char* in_PluginName, epg::Logger& in_Logger)
    {
        if (!in_PluginName)
            return 0;

        NiPluginManager* pluginMgr = NiPluginManager::GetInstance();
        if (!pluginMgr)
        {
            in_Logger.Log(
                epg::LOG_ERROR,
                "Could not find Gamebryo plugin manager.");
            return 0;
        }

        NiPlugin* pkPlugin = pluginMgr->GetPluginByName(in_PluginName);
        if (!pkPlugin)
        {
            in_Logger.Logf(
                epg::LOG_ERROR,
                "Could not find Gamebryo \"%s\" plugin.",
                in_PluginName);
            return 0;
        }

        NiScriptInfoPtr spScript = NiScriptTemplateManager::CreateNewScript();
        spScript->AddPluginInfo(pkPlugin->GetDefaultPluginInfo());

        return spScript;
    }

    //---------------------------------------------------------------------------
    // Open the provided Gamebryo plugin pipeline script.
    //---------------------------------------------------------------------------
    NiScriptInfoPtr OpenGamebryoScript(const char * in_ScriptFileName, epg::Logger& in_Logger)
    {
        NiScriptInfoPtr spScript = NiScriptTemplateManager::OpenScript(
                                            in_ScriptFileName, false);
        if (!spScript)
        {
            in_Logger.Logf(
                epg::LOG_ERROR,
                "Gamebryo script \"%s\" could not be found.",
                in_ScriptFileName);
        }

        return spScript;
    }

    //---------------------------------------------------------------------------
    // Validate and setup the Gamebryo import plugin parameters.
    //---------------------------------------------------------------------------
    bool PrepareGamebryoImportPlugin(
        NiScriptInfoPtr& spImportScript,
        const char* dotXSIFileName,
        epg::Logger& in_Logger)
    {
        // Find the Import plugin - the script _must_ contain _exactly_ one
        // import plugin, or else the import will explicitly fail.
        NiImportPluginInfo* pkImport = NULL;
        for (unsigned int i = 0; i < spImportScript->GetPluginSet().GetSize(); ++i)
        {
            NiPluginInfo* pkPlugin = spImportScript->GetPluginSet().GetAt(i);
            if (pkPlugin && pkPlugin->GetType().EqualsNoCase("IMPORT"))
            {
                if (pkImport)
                {
                    return in_Logger.Logf(
                        epg::LOG_ERROR,
                        "The Gamebryo script \"%s\" contained more than one import plugin.",
                        RetrieveValidString(spImportScript->GetFile(), "import script"));
                }

                pkImport = NiDynamicCast(NiImportPluginInfo, pkPlugin);
            }
        }

        if (pkImport)
        {
            in_Logger.Logf(
                epg::LOG_INFO,
                "Gamebryo input plugin \"%s\" will be used.",
                RetrieveValidString(pkImport->GetName(), "import plugin"));

            NiString strPath; 
            NiString strFile; 
            NiString strExtension;
            NiPluginHelpers::ParseFullPath(dotXSIFileName, strPath, strFile, strExtension);

            pkImport->SetFile(strFile);
            pkImport->SetExtension(strExtension);
            pkImport->SetDirectory(strPath);
            pkImport->SetImportType(NiImportPluginInfo::REPLACE);
        }

        return true;
    }

    //---------------------------------------------------------------------------
    // Validate and setup the Gamebryo export plugin parameters.
    //---------------------------------------------------------------------------
    bool PrepareGamebryoExporter(
        NiScriptInfoPtr& spExportScript,
        const char* nifFileName,
        epg::Logger& in_Logger)
    {
        for (unsigned int i = 0; i < spExportScript->GetPluginSet().GetSize(); ++i)
        {
            NiPluginInfo* pkPlugin = spExportScript->GetPluginSet().GetAt(i);
            if (pkPlugin && pkPlugin->GetType().EqualsNoCase("EXPORT"))
            {
                if (NiExportPluginInfo* pkExport = NiDynamicCast(NiExportPluginInfo, pkPlugin))
                {
                    in_Logger.Logf(
                        epg::LOG_INFO,
                        "Gamebryo output plugin \"%s\" will be used.",
                        RetrieveValidString(pkExport->GetName(), "export plugin"));

                    NiString strPath; 
                    NiString strFile; 
                    NiString strExtension;
                    NiPluginHelpers::ParseFullPath(nifFileName, strPath, strFile, strExtension);

                    pkExport->SetFile(strFile);
                    pkExport->SetExtension(strExtension);
                    pkExport->SetDirectory(strPath);
                }
            }
        }

        return true;
    }

    //---------------------------------------------------------------------------
    // Extract the error and warning logged in the XML log file.
    // Uses the tinyXML library visitor pattern.
    //---------------------------------------------------------------------------
    class GamebryoLogVisitor : public TiXmlVisitor
    {
    public:
        GamebryoLogVisitor(epg::Logger& in_Logger)
            : m_InXSIGamebryoLog(false)
            , m_Logger(in_Logger)
        {
        }

        bool VisitEnter(const TiXmlElement& element, const TiXmlAttribute* firstAttribute)
        {
            if (strcmp(element.Value(), XSI_GAMEBRYO_XML_TAG) == 0)
            {
                m_InXSIGamebryoLog = true;
            }
            else if (element.GetText())
            {
                if (strcmp(element.Value(), XSI_GAMEBRYO_XML_WARNING_TAG) == 0)
                {
                    m_Logger.Log(epg::LOG_WARNING, element.GetText());
                }
                else if (strcmp(element.Value(), XSI_GAMEBRYO_XML_ERROR_TAG) == 0)
                {
                    m_Logger.Log(epg::LOG_ERROR, element.GetText());
                }
            }

            return true;
        }

        bool VisitExit(const TiXmlElement& element)
        {
            if (strcmp(element.Value(), XSI_GAMEBRYO_XML_TAG) == 0)
                m_InXSIGamebryoLog = false;
            return true;
        }

    private:
        bool            m_InXSIGamebryoLog;
        epg::Logger&    m_Logger;
    };

    //---------------------------------------------------------------------------
    // Automatically deletes the temporary dotXSI file.
    //---------------------------------------------------------------------------
    class AutoFileDeleter
    {
    public:
        AutoFileDeleter(const char* in_FileName, bool in_IsTemp)
            : m_FileName(in_FileName)
            , m_IsTemp(in_IsTemp)
        {
        }
        ~AutoFileDeleter()
        {
            if (m_IsTemp)
                ::DeleteFile((const char*)m_FileName);
        }
    protected:
        NiString    m_FileName;
        bool        m_IsTemp;
    };

    //---------------------------------------------------------------------------
    // Copy the XML log into the XSI log.
    //---------------------------------------------------------------------------
    class AutoLogTransfer : public AutoFileDeleter
    {
    public:
        AutoLogTransfer(
            epg::Logger& in_Logger,
            NiXMLLogger& in_XMLLogger,
            const char* in_LogFileName,
            bool in_IsTemp)
        : AutoFileDeleter(in_LogFileName, in_IsTemp)
        , m_Logger(in_Logger)
        , m_XMLLogger(in_XMLLogger)
        {
        }

        ~AutoLogTransfer()
        {
            // Always try to read the XML logging file, if any,
            // and extract all warnings and errors that were logged and
            // copy them in the XSI log so that the XSI end-user can look
            // at them there and not be confused about what failed exactly.
            if (!m_FileName.IsEmpty())
            {
                m_XMLLogger.CloseLog();
                TiXmlDocument xmlDoc;
                if (xmlDoc.LoadFile(m_FileName, TIXML_ENCODING_UTF8))
                {
                    GamebryoLogVisitor visitor(m_Logger);
                    xmlDoc.Accept(&visitor);
                }
                else
                {
                    m_Logger.Logf(
                        epg::LOG_ERROR,
                        "Cannot read XML log file \"%s\" due to \"%s\".",
                        m_FileName, xmlDoc.ErrorDesc());
                }
            }
            else
            {
                m_Logger.Log(
                    epg::LOG_ERROR,
                    "Cannot read XML log file because it doesn't have a file name.");
            }
        }

    protected:
        epg::Logger&    m_Logger;
        NiXMLLogger&    m_XMLLogger;
    };

    //---------------------------------------------------------------------------
    // Verify the result of all Gamebryo plugins.
    //---------------------------------------------------------------------------
    bool VerifyGamebryoPluginResult(
        NiBatchExecutionResultPtr & spResult,
        NiScriptInfoPtr spImportScript,
        epg::Logger& in_Logger)
    {
        bool result = true;

        // First verify that we got as many results as expected. Missing results
        // are often the sign that something didn't do what was expected.
        if (spResult->m_pkPluginResults.GetSize() != spImportScript->GetPluginInfoCount())
        {
            in_Logger.Logf(
                epg::LOG_ERROR,
                "The Gamebryo script \"%s\" failed: didn't get all result expected.",
                RetrieveValidString(spImportScript->GetFile(), "internal"));
            result = false;
        }

        // Verify the result of each individual plugin.
        for (unsigned int i = 0; i < spResult->m_pkPluginResults.GetSize(); ++i)
        {
            NiString pluginName("unknown plugin");
            if (i < spImportScript->GetPluginInfoCount())
            {
                NiPluginInfo* pPluginInfo = spImportScript->GetPluginInfoAt(i);
                if (pPluginInfo)
                {
                    pluginName = pPluginInfo->GetName();
                }
            }

            NiExecutionResultPtr pExecResult = spResult->m_pkPluginResults[i];
            if (pExecResult && pExecResult->m_eReturnCode == NiExecutionResult::EXECUTE_SUCCESS)
            {
                in_Logger.Logf(
                    epg::LOG_INFO,
                    "The Gamebryo plugin \"%s\" succeeded.",
                    (const char *)pluginName);
            }
            else
            {
                result = in_Logger.Logf(
                    epg::LOG_ERROR,
                    "The Gamebryo plugin \"%s\" failed.", pluginName);
            }
        }

        // Verify the overall result.
        if (spResult->WasSuccessful())
        {
            in_Logger.Logf(
                epg::LOG_INFO,
                "Gamebryo script \"%s\" successful.",
                RetrieveValidString(spImportScript->GetFile(), "internal"));
        }
        else
        {
            result = in_Logger.Logf(
                epg::LOG_ERROR,
                "The Gamebryo script \"%s\" failed.",
                RetrieveValidString(spImportScript->GetFile(), "internal"));
        }

        return result;
    }

    //---------------------------------------------------------------------------
}

namespace epg
{
    //---------------------------------------------------------------------------
    // Export a dotXSI file to a NIF using Gamebryo pipeline scripts.
    //---------------------------------------------------------------------------
    bool GamebryoScriptedExport(
        const char* in_dotXSIFileName,
        const char* in_OutputFileName,
        const ConverterSettings& in_Settings,
        Logger& in_Logger)
    {
        if (!epg::LoadAllGamebryoPlugins())
        {
            return in_Logger.Logf(
                LOG_ERROR,
                "Gamebryo engine initialization failed.");
        }

        // Get final export file name.
        if (!in_OutputFileName || !in_OutputFileName[0])
        {
            return in_Logger.Log(
                LOG_ERROR,
                "No output file name selected for Gamebryo export.");
        }

        // Prepare Gamebryo XML logger.
        NiXMLLogger kLogger;
        NiString logFileName;
        bool logIsTemp;
        if (!SetupGamebryoLogging(in_Settings, kLogger, logFileName, logIsTemp))
            return false;
        AutoLogTransfer autoLogTransfer(in_Logger, kLogger, logFileName, logIsTemp);

        // Make sure import will be done relative to the dotXSI file.
        // This is important to be able to find image files.
        AutoChangeCurDir autoChangeCurDir(NiFilename(in_dotXSIFileName).GetDir());

        // Target platform setup.
        if (!SetTargetPlatform(in_Settings.GetTargetPlatform(), in_Logger))
            return false;

        // Create and execute the requested or default script for each conversion step:
        //
        //   - Import dotXSI into a Gamebryo scene.
        //   - Process the Gamebryo scene (ex: remove unused nodes, optimize meshes, etc).
        //   - Export Gamebryo scene into NIF file.
        //   - View the exported NIF file.
        struct ScriptInfo
        {
            const char* (ConverterSettings::*m_ScriptNameFunc)() const;
            const char* (ConverterSettings::*m_ScriptDataFunc)() const;
            const char*  m_DefaultPlugin;
            const char*  m_MessageOnFailure;
        };

        // Note: be careful about hard-coded names of the plugins below.
        // Other Gamebryo code seem to go by magic name, so do we.
        ScriptInfo scriptInfos[] =
        {
            {
                0,
                0,
                "XSI Import Plugin",
                "Import plugin failed."
            },
            {
                &ConverterSettings::GetGamebryoProcessingScript,
                &ConverterSettings::GetGamebryoProcessingScriptEnc,
                0,
                "Processing script failed."
            },
            {
                &ConverterSettings::GetGamebryoExportingScript,
                &ConverterSettings::GetGamebryoExportingScriptEnc,
                "NIF Exporter",
                "Export script failed."
            },
            {
                &ConverterSettings::GetGamebryoViewingScript,
                &ConverterSettings::GetGamebryoViewingScriptEnc,
                in_Settings.GetLaunchGamebryoAssetViewer() ? "NIF Viewer" : 0,
                in_Settings.GetLaunchGamebryoAssetViewer()
                ? "Asset viewer could not be launched." : "Viewing script failed."
            }
        };

        BuildRendererSharedData();

        for (int i = 0; i < sizeof(scriptInfos) / sizeof(scriptInfos[0]); ++i)
        {
            const char* scriptFileName = 0;
            if (scriptInfos[i].m_ScriptNameFunc)
            {
                const char* (ConverterSettings::*func)() const = scriptInfos[i].m_ScriptNameFunc;
                scriptFileName = (in_Settings.*func)();
            }

            // Open or create the Gamebryo plugin pipeline scripts.
            // Note: the smart pointer will delete the script.
            NiScriptInfoPtr spScript;
            if (!scriptFileName || !scriptFileName[0])
            {
                if (scriptInfos[i].m_DefaultPlugin)
                {
                    spScript = CreateDefaultGamebryoScript(
                        scriptInfos[i].m_DefaultPlugin, in_Logger);
                }
                else
                {
                    // No default, go on...
                    continue;
                }
            }
            else
            {
                NiString tempStr = scriptFileName;

                bool bEndsWithScript = false;
                unsigned int uiScriptIndex = tempStr.Find(".script");
                bEndsWithScript = (uiScriptIndex != NiString::INVALID_INDEX &&
                    uiScriptIndex == tempStr.Length() - 7);
                
                if (bEndsWithScript)
                {
                    spScript = OpenGamebryoScript(scriptFileName, in_Logger);
                }
                else if (tempStr.Length() > 0)
                {
                    if (scriptInfos[i].m_ScriptDataFunc)
                    {
                        const char* (ConverterSettings::*func)() const = 
                            scriptInfos[i].m_ScriptDataFunc;
                        NiString scriptData = (in_Settings.*func)();
                        NiString strErrors;

                        NiDefaultScriptReader kReader;
                        spScript = kReader.Parse(scriptData, strErrors, true);
                    }
                }
            }

            if (!spScript)
                return in_Logger.Log(LOG_ERROR, scriptInfos[i].m_MessageOnFailure);

            // Prepare, setup and execute the script.
            if (!PrepareGamebryoImportPlugin(spScript, in_dotXSIFileName, in_Logger))
                return in_Logger.Log(LOG_ERROR, scriptInfos[i].m_MessageOnFailure);

            if (!PrepareGamebryoExporter(spScript, in_OutputFileName, in_Logger))
                return in_Logger.Log(LOG_ERROR, scriptInfos[i].m_MessageOnFailure);

            NiBatchExecutionResultPtr spResult =
                NiFramework::GetFramework().ExecuteScript(spScript);
            
            // Returning false on failure here so that the calling
            // function knows when export fails.
            // bsowers 9/9/08
            if (!VerifyGamebryoPluginResult(spResult, spScript, in_Logger))
                return in_Logger.Log(LOG_ERROR,  scriptInfos[i].m_MessageOnFailure);
        }

        DeleteAllSharedData();

        return true;
    }

    //---------------------------------------------------------------------------
    void BuildRendererSharedData()
    {
        NiFramework& kFramework = NiFramework::GetFramework();
        NiSharedDataList& kSharedDataList = kFramework.GetSharedDataList();

        // Lock the shared data list so other thread don't use it
        kSharedDataList.Lock();

        // Build the Shared Data
        NiRendererSharedDataPtr spRenderer = NiNew NiRendererSharedData;

        // Set the Renderer Values
        spRenderer->SetBackgroundColor(NiColor(0, 0, 0));

        spRenderer->SetFullscreen(false);
        spRenderer->SetWindowSize(NiPoint2(800.0f, 600.0f));

        kSharedDataList.Insert(spRenderer);
        kSharedDataList.Unlock();
    }

    
    
    //---------------------------------------------------------------------------
    void DeleteAllSharedData()
    {
        NiFramework& kFramework = NiFramework::GetFramework();
        NiSharedDataList& kSharedDataList = kFramework.GetSharedDataList();

        // Lock the shared data list so other thread don't use it
        kSharedDataList.Lock();

        // Delete the SceneGraphSharedData
        kSharedDataList.DeleteAll();

        // UnLock the shared data list so other thread don't use it
        kSharedDataList.Unlock();
    }

}
