// EMERGENT GAME TECHNOLOGIES PROPRIETARY INFORMATION
//
// This software is supplied under the terms of a license agreement or
// nondisclosure agreement with Emergent Game Technologies and may not 
// be copied or disclosed except in accordance with the terms of that 
// agreement.
//
//      Copyright (c) 1996-2008 Emergent Game Technologies.
//      All Rights Reserved.
//
// Emergent Game Technologies, Chapel Hill, North Carolina 27517
// http://www.emergent.net

// Gamebryo Export Plugin
// Initial code generated by XSI SDK Wizard
// Executed Fri Feb 22 12:01:24 EST 2008 by pbaillargeon
// 
// Tip: You need to compile the generated code before you can load the plugin.
//      You might also need what is known in "the business" as a "compiler".
//      Oh!, and maybe a computer also. And electricity. Yeah, electricity
//      is probably needed. The universe might also be a pre-requisite,
//      we're not sure yet.
// After you compile the plugin, you can load it by clicking Update All in the Plugin Manager.

#include "CrosswalkGamebryoConverter.h"
#include "CrosswalkGamebryoInit.h"
#include "CrosswalkGamebryoLogger.h"
#include "CrosswalkGamebryoHelpers.h"

#include "Scene.h"

#include "NiDevImageConverter.h"
#include "NiHDRReader.h"
#include "NiOpenEXRReader.h"
#include "NiPNGReader.h"

#include "NiPluginToolkit.h"
#include "NiXMLLogger.h"
#include "NiExporterOptionsSharedData.h"
#include "NiFilename.h"
#include "NiMain.h"
#include "NiMesh.h"
#include "NiMorphWeightsController.h"
#include "NiTransformController.h"

#include <direct.h>

//---------------------------------------------------------------------------
// Helpers
//---------------------------------------------------------------------------
namespace
{
    //---------------------------------------------------------------------------
    // Automatically change the current directory. Helps find image files.
    //---------------------------------------------------------------------------
    class AutoChangeCurDir
    {
    public:
        AutoChangeCurDir(const char* in_NewCurDir)
        {
            char* cwd = _getcwd(NULL, 0);
            if (cwd)
            {
                m_PrevCurDir = cwd;
                free(cwd);
            }
            _chdir(in_NewCurDir);
        }
        ~AutoChangeCurDir()
        {
            if (m_PrevCurDir.size() > 0 )
                _chdir(m_PrevCurDir.c_str());
        }

    private:
        std::string m_PrevCurDir;
    };

    //---------------------------------------------------------------------------
    // Automatically deletes the temporary dotXSI file.
    //---------------------------------------------------------------------------
    class AutoFileDeleter
    {
    public:
        AutoFileDeleter(const char* in_FileName, bool in_IsTemp)
            : m_FileName(in_FileName)
            , m_IsTemp(in_IsTemp)
        {
        }
        ~AutoFileDeleter()
        {
            if (m_IsTemp)
                ::DeleteFile((const char*)m_FileName);
        }
    protected:
        NiString    m_FileName;
        bool        m_IsTemp;
    };

    //---------------------------------------------------------------------------
    // Automatically sets and reset the default Gamebryo image converter.
    //---------------------------------------------------------------------------
    class AutoImageConverter
    {
    public:
        AutoImageConverter()
            : m_PrevImageConverter(NiImageConverter::GetImageConverter())
        {
            m_OpenEXRReader = NiNew NiOpenEXRReader;
            m_HDRReader = NiNew NiHDRReader;
            m_PNGReader = NiNew NiPNGReader;

            // Note: NiDevImageConverter doesn't declare its Ptr,
            //       so take the easy way out and keep it as
            //       a NiImageConverter instead... but we do need
            //       access to its AddReader() function here too.
            NiDevImageConverter* converter = NiNew NiDevImageConverter;
            m_ImageConverter = converter;
            converter->AddReader(m_OpenEXRReader);
            converter->AddReader(m_HDRReader);
            converter->AddReader(m_PNGReader);

            // Note: do this last so that exceptions leave the
            //       original default converter registered.
            NiImageConverter::SetImageConverter(m_ImageConverter);
        }

        ~AutoImageConverter()
        {
            // Note: this automatically deletes the m_ImageConverter.
            //       The NiDevImageConverter destructor will automatically
            //       delete all registered image readers, so don't delete
            //       them either.
            NiImageConverter::SetImageConverter(m_PrevImageConverter);
        }

    private:
        // Note: declare reader before converter so they are deleted afterward.
        NiOpenEXRReader*            m_OpenEXRReader;
        NiHDRReader*                m_HDRReader;
        NiPNGReader*                m_PNGReader;
        NiImageConverterPtr         m_PrevImageConverter;
        NiImageConverterPtr         m_ImageConverter;
    };

    //---------------------------------------------------------------------------
}

namespace epg
{
    //---------------------------------------------------------------------------
    // Export a dotXSI file to a NIF directly.
    //---------------------------------------------------------------------------
    bool GamebryoDirectExport(
        const char* in_dotXSIFileName,
        const char* in_OutputFileName,
        bool in_IgnoreAllErrors,
        epg::TargetPlatform in_Platform,
        Logger& in_Logger,
        ProgressMonitor& in_Progress)
    {
        CSLScene scene;
        SI_Error error = scene.Open((SI_Char*)in_dotXSIFileName);
        if (SI_SUCCESS != error)
            return in_Logger.Logf(LOG_ERROR, "Cannot open \"%s\".", in_dotXSIFileName);

        if (SI_SUCCESS != scene.Read())
        {
            return in_Logger.Logf(
                LOG_ERROR,
                "Cannot read \"%s\". (Corrupted file?)",
                in_dotXSIFileName);
        }

        // Register additional image converters.
        AutoImageConverter autoImageConverter;

        // Make sure import will be done relative to the dotXSI file.
        // This is important to be able to find image files.
        // We change the durrent directory after opening the input
        // file in case the input file name was relative.
        AutoChangeCurDir autoChangeCurDir(NiFilename(in_dotXSIFileName).GetDir());

        ConverterSettings settings;
        LoadSettings(*scene.Root(), settings);
        if (in_IgnoreAllErrors)
            settings.SetIgnoreAllErrors(in_IgnoreAllErrors);
        if (UNKNOWN_PLATFORM != in_Platform)
            settings.SetTargetPlatform(in_Platform);

        Converter converter(settings);
        converter.SetLogger(in_Logger);
        converter.SetProgressMonitor(in_Progress);

        if (! converter.Convert(scene))
            return false;

        NiStream stream;
        NodeMap & nodeMap = converter.GetNodeMap();
        NodeMap::RootObjects & roots = nodeMap.GetRoots();
        typedef NodeMap::RootObjects::iterator iter;
        int namelessRootCount = 0;
        for (iter pos = roots.begin(); pos != roots.end(); ++pos)
        {
            // Note: animation tool doesn't like nameless roots.
            if (!(*pos)->GetName().Exists() || 0 == (*pos)->GetName().GetLength())
            {
                NiString name;
                name.Format("Root-%d", ++namelessRootCount);
                (*pos)->SetName(NiFixedString(name));
            }
            stream.InsertObject(*pos);
        }

        if (!stream.Save(in_OutputFileName))
        {
            return in_Logger.Logf(
                LOG_ERROR,
                "Cannot save Gamebryo objects to file \"%s\".",
                in_OutputFileName);
        }

        return true;
    }

    //---------------------------------------------------------------------------
}
