// EMERGENT GAME TECHNOLOGIES PROPRIETARY INFORMATION
//
// This software is supplied under the terms of a license agreement or
// nondisclosure agreement with Emergent Game Technologies and may not 
// be copied or disclosed except in accordance with the terms of that 
// agreement.
//
//      Copyright (c) 1996-2008 Emergent Game Technologies.
//      All Rights Reserved.
//
// Emergent Game Technologies, Chapel Hill, North Carolina 27517
// http://www.emergent.net

// Gamebryo Export Plugin
// Initial code generated by XSI SDK Wizard
// Executed Fri Feb 22 12:01:24 EST 2008 by pbaillargeon
// 
// Tip: You need to compile the generated code before you can load the plugin.
//      You might also need what is known in "the business" as a "compiler".
//      Oh!, and maybe a computer also. And electricity. Yeah, electricity
//      is probably needed. The universe might also be a pre-requisite,
//      we're not sure yet.
// After you compile the plugin, you can load it by clicking Update All in the Plugin Manager.

#include "CrosswalkGamebryoInit.h"

#include "NiMain.h"
#include "NiMesh.h"
#include "NiPluginToolkit.h"
#include "NiMeshProfileProcessor.h"
#include "NiMeshProfileXMLParser.h"
#include "NiMaterialToolkit.h"

#include <set>
#include <string>

//---------------------------------------------------------------------------
// Gamebryo engine initialization management.
//
// Engine cannot be initialized multiple times, even when shutting down
// in between. Plus, XSI freezes if the Gamebryo engine is initialized
// when the plugin is loaded. So we use functions to delay the initialization
// and ensure the shutdown.
//---------------------------------------------------------------------------
namespace
{
    //---------------------------------------------------------------------------
    // Necessary object to ensure that the Gamebryo DLLs get registered
    // properly with the Gamebryo static data manager (SDM).
    //---------------------------------------------------------------------------
    static NiMainSDM NiMainSDMObject;
    static NiMeshSDM NiMeshSDMObject;
    static NiPluginToolkitSDM NiPluginToolkitSDMObject;

    //---------------------------------------------------------------------------
    // Control how many times the Gamebryo engine has been initialized
    // in this particular DLL.
    //---------------------------------------------------------------------------
    std::set<std::string> gGamebryoInitializers;
    bool gGamebryoPluginLoaded;
    bool gGamebryoPluginLoadResult;

    //---------------------------------------------------------------------------
    // Retrieve where the plugin are found.
    //---------------------------------------------------------------------------
    NiString GetGamebryoPluginPath()
    {
        // Get plugin directory.
#if defined(_MSC_VER) && _MSC_VER >= 1400
        char acPluginPath[NI_MAX_PATH];
        unsigned int uiPathLen = 0;
        const char* pcPluginPath = NULL;
        if (getenv_s(&uiPathLen, acPluginPath, NI_MAX_PATH, 
            "EGB_TOOL_PLUGIN_PATH") != 0 || uiPathLen > NI_MAX_PATH)
        {
            acPluginPath[0] = '\0';
        }
        else
        {
            pcPluginPath = acPluginPath;
        }
#else //#if defined(_MSC_VER) && _MSC_VER >= 1400
        const char* pcPluginPath = getenv("EGB_TOOL_PLUGIN_PATH");
#endif //#if defined(_MSC_VER) && _MSC_VER >= 1400

        return pcPluginPath ? pcPluginPath : "";
    }

    //---------------------------------------------------------------------------
    // Retrieve the path to the current application.
    //---------------------------------------------------------------------------
    void GetAppPath(char * acAppPath, size_t capacity)
    {
        acAppPath[0] = '\0';
        ::GetModuleFileName(NULL, acAppPath, capacity);
        char* pcPtr = strrchr(acAppPath, '\\');
        if (pcPtr)
            pcPtr[1] = '\0';
    }

    //---------------------------------------------------------------------------
    // Manage the Gamebryo engine initialization and shutdown via a count
    // kept in an environment variable protected by a mutex.
    //
    // This is used to protect the Gamebryo initialization and shutdown accross
    // multiple DLLs inside a single process that don't know about each others.
    // For example, the export DLL and material DLL in XSI are independent but
    // both need access to the shared Gamebryo engine.
    //
    // We use a public mutex so each DLL can protect and serialize the
    // initialization and shutdown. The advantage of a mutex is that in case
    // of a crash the mutex is automatically released if it was held, unlike
    // an event or a semaphore.
    //
    // Using an environment variable allows a shared state using a simple API.
    // Using shared memory would be more complicated because the name of the
    // shared memory would have to be unique and it has no protection when
    // a crash occurs. Environment variables are per-process and thus have no
    // issue with name clash between processes and their state after a crash.
    //---------------------------------------------------------------------------

    static const char gGamebryoInitEnvName[]   = "CrosswalkGamebryoInitCount";
    static const char gGamebryoInitMutexName[] = "CrosswalkGamebryoInitMutex";

    class GamebryoInitProtector
    {
    public:
        // Constructor, grabs a public mutex.
        GamebryoInitProtector()
            : m_Mutex(::CreateMutex(0, 0, gGamebryoInitMutexName))
        {
            if (m_Mutex)
                ::WaitForSingleObject(m_Mutex, INFINITE);
        }

        // Destructor, release the public mutex.
        ~GamebryoInitProtector()
        {
            if (m_Mutex)
                ::ReleaseMutex(m_Mutex);
        }

        // Increase the reference count on the Gamebryo engine.
        // \return true if you are the first user and really must initialize.
        bool IncreaseRefCount()
        {
            return 0 == ModifyRefCount(1);
        }

        // Decrease the reference count on the Gamebryo engine.
        // \return true if you are the last user and really must shutdown.
        bool DecreaseRefCount()
        {
            return 1 == ModifyRefCount(-1);
        }


    private:
        // Modify the reference count on the Gamebryo engine by the specified amount.
        // \return the previous value.
        int ModifyRefCount(int in_Amount)
        {
            int previousValue = 0;

            if (m_Mutex)
            {
                // Fetch the previous value from the environment. Non-existing means zero.
                char buffer[32];
                DWORD result = ::GetEnvironmentVariable(
                    gGamebryoInitEnvName, buffer, sizeof(buffer) / sizeof(buffer[0]));
                if (result && result < sizeof(buffer) / sizeof(buffer[0]))
                {
                    previousValue = atoi(buffer);
                }

                // Update the value, but only if it is a valid value,
                // i.e. greater or equal to zero.
                const int newValue = previousValue+in_Amount;
                if (newValue >= 0)
                {
                    sprintf(buffer, "%d", newValue);
                    if (0 == ::SetEnvironmentVariable(gGamebryoInitEnvName, buffer))
                    {
                        previousValue = -1;
                    }
                }
                else
                {
                    previousValue = -1;
                }
            }

            return previousValue;
        }

        HANDLE      m_Mutex;
    };

    //---------------------------------------------------------------------------
}

namespace epg
{
    //---------------------------------------------------------------------------
    // Initialize the Gamebryo engine if needed.
    //---------------------------------------------------------------------------
    void InitializeGamebryo(const char * in_InitializerName)
    {
        NIASSERT(in_InitializerName);
        NIASSERT(in_InitializerName[0]);

        if (0 == gGamebryoInitializers.size())
        {
            GamebryoInitProtector initProtector;
            if (initProtector.IncreaseRefCount())
            {
                // Note: this call must be made *instead* of NiInit() when using
                //       the plugin framework.
                char acAppPath[_MAX_PATH];
                GetAppPath(acAppPath, sizeof(acAppPath) / sizeof(acAppPath[0]));
                NiFramework::InitFramework(
                    acAppPath,
                    in_InitializerName,
                    GAMEBRYO_SDK_VERSION_STRING);

                // The following was taken from the batch plugin tool.
                // We assume it knows what it's doing. :-)
                NiSystemDesc::GetSystemDesc().SetToolMode(true);
                NiSystemDesc::GetSystemDesc().SetToolModeRendererID(
                    NiSystemDesc::RENDERER_GENERIC);
                NiShadowManager::Initialize();
                // Because this is a tool that may not have loaded all available shaders,
                // don't remove any shaders that can't be loaded when loading assets.
                // This will allow for processing of assets even if their shaders
                // are not currently available.
                NiMaterialLibrary::SetCreateReturnsNullIfMissingFlag(false);

                NiMaterialToolkit::CreateToolkit();
            }
        }

        gGamebryoInitializers.insert(in_InitializerName);
    }

    //---------------------------------------------------------------------------
    // Load all Gamebryo pipeline plugins.
    //---------------------------------------------------------------------------
    bool LoadAllGamebryoPlugins()
    {
        if (gGamebryoPluginLoaded)
            return gGamebryoPluginLoadResult;

        gGamebryoPluginLoadResult = false;

        NiString pluginPath = GetGamebryoPluginPath();
        if (!pluginPath.IsEmpty())
        {
            // Parse the plugin directory path(s)
            NiStringTokenizer strTok(pluginPath);
            while (!strTok.IsEmpty())
            {
                NiString strPath = strTok.GetNextToken(";");
                int iPtr = strPath.FindReverse('\\');
                NIASSERT(iPtr >= 0);
                if ((unsigned int) iPtr < strPath.Length() - 1)
                {
                    strPath += '\\';
                }

#if _MSC_VER == 1310 //VC7.1
            strPath += "Lib\\VC71\\";
#elif _MSC_VER == 1400 //VC8.0
            strPath += "Lib\\VC80\\";
#elif _MSC_VER == 1500 //VC9.0
            strPath += "Lib\\VC90\\";
#else
        #error Unsupported version of Visual Studio
#endif

                // This does the actual loading of all plugins.
                NiPluginManager::GetInstance()->AddPluginDirectory(
                    strPath, true, true);
            }

            NiMeshProfileProcessor::CreateMeshProfileProcessor();
            NiMeshProfileXMLParser::RegisterAllProfilesWithProcessor();

            gGamebryoPluginLoaded = true;
            gGamebryoPluginLoadResult = true;
        }

        return gGamebryoPluginLoadResult;
    }

    //---------------------------------------------------------------------------
    // Decrement the usage count of the Gamebryo engine, shut it down when last
    // user is done.
    //---------------------------------------------------------------------------
    void ShutdownGamebryo(const char * in_InitializerName, bool avoidXSICrash)
    {
        // Note: avoidXSICrash is a legacy. We keep it around for now in
        //       case it's needed again, but it might be removed in a future
        //       version.
        gGamebryoInitializers.erase(in_InitializerName);
        if (0 == gGamebryoInitializers.size())
        {
            GamebryoInitProtector initProtector;
            if (initProtector.DecreaseRefCount())
            {
                NiMaterialToolkit::DestroyToolkit();
                NiMeshProfileProcessor::DestroyMeshProfileProcessor();
                NiShadowManager::Shutdown();
                // Note: this call must be made *instead* of NiShutdown() when using
                //       the plugin framework.
                NiFramework::ShutdownFramework();
            }

            gGamebryoPluginLoaded = false;
        }
    }

    //---------------------------------------------------------------------------
}
