//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GamebryoShaders.rc
//
#define IDF_SHADEFILE_VERTEX_01_PHONG   1010
#define IDF_SHADEFILE_FRAGMENT_01_PHONG 1011
#define IDF_SHADEFILE_VERTEX_02_DIFFUSEMAP1 1012
#define IDF_SHADEFILE_FRAGMENT_02_DIFFUSEMAP1 1013
#define IDF_SHADEFILE_VERTEX_03_DIFFUSEMAP2 1014
#define IDF_SHADEFILE_FRAGMENT_03_DIFFUSEMAP2 1015
#define IDF_SHADEFILE_VERTEX_04_BUMPMAP 1016
#define IDF_SHADEFILE_FRAGMENT_04_BUMPMAP 1017
#define IDF_SHADEFILE_VERTEX_00_PASSTHROUGH 1018
#define IDF_SHADEFILE_FRAGMENT_00_PASSTHROUGH 1019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
